# Enhanced Blind Detection System - Unified Configuration
# Multiple scenarios in one file - use scenario parameter to select

# Default scenario configuration
default:
  # Model settings
  model_name: 'yolov8n.pt'    # YOLOv8 nano model (fastest, good for real-time)
  confidence_threshold: 0.5   # Minimum confidence for detections (0.0-1.0)
  device: 'auto'              # Device selection: 'auto', 'cpu', or 'cuda'
  
  # Camera settings
  camera_index: 0             # Camera device index (usually 0 for default camera)
  frame_width: 640            # Frame width in pixels
  frame_height: 480           # Frame height in pixels
  
  # Audio settings
  voice_rate: 200             # Speech rate (50-400 words per minute)
  voice_volume: 0.9           # Speech volume (0.0-1.0)
  announcement_cooldown: 2.0  # Seconds between repeated announcements
  
  # Detection settings - Common objects
  target_classes:
    - 'person'
    - 'chair'
    - 'table'
    - 'sofa'
    - 'bed'
    - 'tv'
    - 'laptop'
    - 'book'
    - 'bottle'
    - 'cup'
  
  # Spatial analysis settings
  distance_thresholds:
    close: 0.3              # Objects with bbox area > 30% of frame
    medium: 0.1             # Objects with bbox area 10-30% of frame
    far: 0.0                # Objects with bbox area < 10% of frame

# Indoor navigation scenario
indoor:
  # Model settings - Balanced performance
  model_name: 'yolov8s.pt'
  confidence_threshold: 0.55
  device: 'auto'
  
  # Camera settings - Standard resolution
  camera_index: 0
  frame_width: 640
  frame_height: 480
  
  # Audio settings - Comfortable speech rate
  voice_rate: 200
  voice_volume: 0.9
  announcement_cooldown: 2.0
  
  # Detection settings - Indoor-focused objects
  target_classes:
    # People and pets (highest priority)
    - 'person'
    - 'cat'
    - 'dog'
    # Furniture (navigation obstacles)
    - 'chair'
    - 'table'
    - 'sofa'
    - 'bed'
    - 'toilet'
    # Electronics and appliances
    - 'tv'
    - 'laptop'
    - 'microwave'
    - 'oven'
    - 'refrigerator'
    # Common household items
    - 'potted plant'
    - 'vase'
    - 'book'
    - 'bottle'
    - 'cup'
    - 'backpack'
    - 'suitcase'
  
  # Spatial analysis settings
  distance_thresholds:
    close: 0.4
    medium: 0.15
    far: 0.05

# Outdoor navigation scenario
outdoor:
  # Model settings - Higher accuracy for complex outdoor scenes
  model_name: 'yolov8m.pt'
  confidence_threshold: 0.6
  device: 'auto'
  
  # Camera settings - Higher resolution for distant objects
  camera_index: 0
  frame_width: 1280
  frame_height: 720
  
  # Audio settings - Louder and clearer for outdoor use
  voice_rate: 220
  voice_volume: 1.0
  announcement_cooldown: 1.8
  
  # Detection settings - Outdoor-focused objects
  target_classes:
    # People and animals (highest priority)
    - 'person'
    - 'dog'
    - 'cat'
    - 'bird'
    # Vehicles (safety critical)
    - 'bicycle'
    - 'car'
    - 'motorcycle'
    - 'bus'
    - 'truck'
    # Street furniture and obstacles
    - 'bench'
    - 'chair'
    - 'potted plant'
    - 'fire hydrant'
    - 'stop sign'
    - 'parking meter'
    # Outdoor equipment
    - 'umbrella'
    - 'backpack'
    - 'suitcase'
    - 'sports ball'
    - 'skateboard'
    - 'surfboard'
  
  # Spatial analysis settings
  distance_thresholds:
    close: 0.25
    medium: 0.08
    far: 0.02

# High performance scenario (for powerful hardware)
high_performance:
  # Model settings - Maximum accuracy
  model_name: 'yolov8l.pt'
  confidence_threshold: 0.4
  device: 'cuda'  # Prefer GPU if available
  
  # Camera settings - High resolution
  camera_index: 0
  frame_width: 1920
  frame_height: 1080
  
  # Audio settings
  voice_rate: 250
  voice_volume: 0.9
  announcement_cooldown: 1.5
  
  # Detection settings - All important objects
  target_classes:
    # People and animals
    - 'person'
    - 'cat'
    - 'dog'
    - 'bird'
    - 'horse'
    - 'sheep'
    - 'cow'
    # Vehicles
    - 'bicycle'
    - 'car'
    - 'motorcycle'
    - 'airplane'
    - 'bus'
    - 'train'
    - 'truck'
    - 'boat'
    # Furniture
    - 'bench'
    - 'chair'
    - 'couch'
    - 'bed'
    - 'dining table'
    - 'toilet'
    # Electronics
    - 'tv'
    - 'laptop'
    - 'mouse'
    - 'remote'
    - 'keyboard'
    - 'cell phone'
    # Kitchen items
    - 'microwave'
    - 'oven'
    - 'toaster'
    - 'sink'
    - 'refrigerator'
    - 'bottle'
    - 'wine glass'
    - 'cup'
    - 'fork'
    - 'knife'
    - 'spoon'
    - 'bowl'
    # Sports and recreation
    - 'frisbee'
    - 'skis'
    - 'snowboard'
    - 'sports ball'
    - 'kite'
    - 'baseball bat'
    - 'baseball glove'
    - 'skateboard'
    - 'surfboard'
    - 'tennis racket'
    # Accessories
    - 'backpack'
    - 'umbrella'
    - 'handbag'
    - 'tie'
    - 'suitcase'
    - 'book'
    - 'clock'
    - 'vase'
    - 'scissors'
    - 'teddy bear'
    - 'hair drier'
    - 'toothbrush'
    - 'potted plant'
  
  # Spatial analysis settings
  distance_thresholds:
    close: 0.35
    medium: 0.12
    far: 0.03

# Low resource scenario (for older/slower hardware)
low_resource:
  # Model settings - Fastest processing
  model_name: 'yolov8n.pt'
  confidence_threshold: 0.6
  device: 'cpu'  # Force CPU to save GPU memory
  
  # Camera settings - Lower resolution
  camera_index: 0
  frame_width: 320
  frame_height: 240
  
  # Audio settings
  voice_rate: 180
  voice_volume: 0.8
  announcement_cooldown: 3.0
  
  # Detection settings - Essential objects only
  target_classes:
    - 'person'
    - 'chair'
    - 'table'
    - 'car'
    - 'bicycle'
    - 'bottle'
    - 'cup'
  
  # Spatial analysis settings
  distance_thresholds:
    close: 0.5
    medium: 0.2
    far: 0.1

# Usage instructions:
# python run_app.py --scenario default
# python run_app.py --scenario indoor
# python run_app.py --scenario outdoor
# python run_app.py --scenario high_performance
# python run_app.py --scenario low_resource
